### ISSUE TITLE
Question about install

### ISSUE THREAD

**Issue by eGavr** [nickhutchinson/libdispatch#13]
Can you give more detail info about installation of Prerequisities?

**Comment by nickhutchinson** [comment]
The kqueue, pthread_workqueue and blocksRuntime packages as provided by Ubuntu >= 12.04 seem to work. If you're on a Debian-based distro, then installing the following packages should do the trick:

- libpthread-workqueue-dev
- libblocksruntime-dev
- libkqueue-dev
- clang
- cmake

If not, then you'll have to build and install libpthread-workqueue, blocksRuntime and libkqueue from source. Links to the repos are in Readme.md.

I'm working on making this easier. Kqueue especially is quite buggy, so I want to bundle a version that's known to work rather than relying on distro supplied versions, or having users build and install versions they've tracked down themselves.

I'm also working on a configure script that invokes cmake for you, because cmake's command line options aren't very user friendly.

Does that help?
